// Generated by CoffeeScript 1.7.1
var Module, Request,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Module = require('./utils/module');

module.exports = Request = (function(_super) {
  __extends(Request, _super);

  function Request(req) {
    Request.__super__.constructor.apply(this, arguments);
    Module.extend.call(this, req);
    this;
  }

  Request.prototype.set_env = function(env) {
    var key, name, value, _ref, _results;
    _ref = this.headers;
    _results = [];
    for (key in _ref) {
      value = _ref[key];
      name = ('http_' + key.replace('-', '_')).toUpperCase();
      _results.push(env[name] = value);
    }
    return _results;
  };

  return Request;

})(Module);
