// Generated by CoffeeScript 1.7.1
var Module, Response,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Module = require('./utils/module');

module.exports = Response = (function(_super) {
  __extends(Response, _super);

  function Response(req) {
    Response.__super__.constructor.apply(this, arguments);
    Module.extend.call(this, req);
    this;
  }

  Response.prototype.set_env = function(env) {
    this.env = env;
    return this.request = env.request;
  };

  return Response;

})(Module);
